<form method="POST">
<header>
    <h1><input name="title" value=<?= $article->title ?>></h1>
</header>
<section>
    <div>
        <label>Url:</label><input name="url" value=<?= "'".$article->slug."'" ?> />
        <label>Popis:</label><input name="description" value=<?= "'".$article->description."'" ?> />
        <label>Klíčová slova:</label><input name="key_words" value=<?= "'".$article->keyWords."'" ?> />
    </div>
</section>
<section>
    <textarea name="content">
    <?= $article->content ?>
    </textarea>
    <button>Odeslat</button>
</section>