<!DOCTYPE html>
<html lang="cs-cz">
    <head>
        <base href="/localhost" />
        <meta charset="UTF-8" />
        <title><?= $pageTitle ?></title>
        <meta name="description" content="<?= $metaDescription ?>" />
        <meta name="keywords" content="<?= $metaKeywords ?>" />
        <link rel="stylesheet" href="style.css" type="text/css"/>
    </head>

    <body>
        <header>
            <h1>DevbookMVC - ukázkový web</h1>
            <nav>
                <ul>
                    <li><a href="clanek/uvod">Úvod</a></li>
                    <li><a href="clanek">Články</a></li>
                    <li><a href="kontakt">Kontakt</a></li>
                </ul>
            </nav>
        </header>
        <article>
            <?php $this->controller->returnView(); ?>
        </article>
    </body>
</html>